version: '3'
services:
  application-service:
    build: ./dist/fleetdatabaseFinal/
    command: /usr/fleetdatabaseFinal/production.pex fleetdatabaseFinal.wsgi -- bind 0.0.0.0:5000
    expose:
      - 5000
    
    
  #db:
    #image: postgres:14.1-alpine
    #restart: always
    #environment:
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=postgres
    #ports:
      #- '5432:5432'
    #volumes: 
      #- db:/var/lib/postgresql/data

#volumes:
  #db:
    #driver: local
  
