# Generated by Django 4.1.7 on 2023-05-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='Tyre_code',
            field=models.CharField(db_column='Tyre_code', max_length=45, primary_key=True, serialize=False, unique=True),
        ),
    ]
